[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
fs_permissions = [{ access = "read-write", path = "../" }]

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
